- .github/workflows/build.yml
Adds an action to push the application-service operator's image to quay.io/redhat-appstudio/application-service:<sha> (and latest)
> Add action for pushing to quay.io

- controllers/application_controller.go
Fixes https://issues.redhat.com/browse/DEVHAS-60
The way we're currently attaching the Application finalizer to Application resources in HAS is problematic, and there's a chance (about 1/3 from my observations) that the reconcile loop will be triggered twice, resulting in the following error:
```
2022-01-12T17:43:49.613-0500	ERROR	controllers.Application	Unable to update Application	{"Application": "application-sample", "error": "Operation cannot be fulfilled on applications.appstudio.redhat.com \"application-sample\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/redhat-appstudio/application-service/controllers.(*ApplicationReconciler).Reconcile
/Users/johncollier/appstudio/application-service/controllers/application_controller.go …
```
> [DEVHAS-60] Return after adding the finalizer to reset reconcile loop

- controllers/application_controller_test.go
- controllers/component_controller_test.go
Updates the controller test case names.
It seems like the kubeClient used for the test sometimes runs into issues when using the same name for Kube resources. Even after a delete op is performed, it complains about a resource being present.
> Update controller test case intermittent bug

- pkg/util/util.go
- pkg/util/util_test.go
Fixes https://issues.redhat.com/browse/DEVHAS-63
Updates the `util.ConvertGitHubURL` function to treat GitHub URLs with `.git` at the end as valid.
> Treat URLs with .git as valid

- controllers/component_controller.go
- controllers/component_controller_test.go
- controllers/componentdetectionquery_controller.go
Fixes https://issues.redhat.com/browse/DEVHAS-64
Just adding this for the Component and ComponentDetectionQuery CRs for now.
Leaving it out for the Application CR for now, cause there may be scenarios in the future where we want to trigger a reconcile loop upon modifying the App Model's status (specifically the app model devfile).
> [DEVHAS-64] Don't watch for changes to Component's status

- controllers/component_controller.go
Tested this change, and 100% of the time the route information could be fetched. Hope it actually works ;) Either way, this change stops reporting the error because it's clearly a false positive. Worst case, the `status.webhook` url shows up in the next reconcile.
I'll follow up with something more sophisticated.
> Add a simple retry logic for fetching the route after creation

- controllers/application_controller.go
- controllers/component_controller.go
- controllers/componentdetectionquery_controller.go
Don't reconcile upon every error
Fixes https://issues.redhat.com/browse/DEVHAS-69
This PR updates HAS so that we don't return error from the Reconcile() function after every error that is encountered. For the following errors, we now return `ctrl.Result{}, nil` instead of `ctrl.Result{}:
**Application**
- Failure to convert Application CR to devfile
- Unable to marshall Application devfile to yaml
**Component**
- Unable to convert Github URL to raw format 
- Unable to read the devfile from github repository
- Unable to GET the devfile from URL
- Unable to parse the Component devfile
- Unable to update the Component Devfile model
- Unable to parse the Application devfile
- Unable to update the Application Devfile model
- Unable to marshall the Component devfile
- Unable to marshall the …
> [DEVHAS-69] Don't return an error upon every reconcile error in HAS

- .github/workflows/codecov.yml
Fixes the issue where code coverage reports were getting uploaded on PRs, messing with our reported code coverage percentage.
> Only upload to code coverage reports on pushes to main

- controllers/component_controller.go
- controllers/component_controller_test.go
- hack/routecrd/route.yaml
I saw that the runtime of the tests had nearly doubled from ~35s to ~65s. Doing some debugging, I saw that it was due to us [sleeping while we wait for the Route resource to appear](https://github.com/redhat-appstudio/application-service/blob/main/controllers/component_controller.go#L454).
Instead of sleeping, I updated the code that gets the route to return and requeue itself if the route isn't found. This is an approach we've used in the past with the [devfile registry operator](https://github.com/devfile/registry-operator/blob/main/controllers/devfileregistry_controller.go#L119), as it seems to help refresh the cached Kube client faster, allowing it to pick up the created route quicker than sleeping
I also updated the tests for these changes. To do so, I manually update the route's …
> Don't sleep if EventListener route can't be found

- controllers/component_controller.go
Slight tweak to the logic in https://github.com/redhat-appstudio/application-service/pull/46
There's no point in attempting to get the EventListener route (and requeueing if it fails) if the build generation failed, so we should only attempt to retrieve it if the build generation succeeded 
- Since there's no specific build generation status condition at the moment, checking if the most recent status condition's status is True should be sufficient for now
> Don't get the EL route if build generation failed

- .tekton/pull-request.yaml
Following changes were made in this PR:
1. Use the existing PVC using a subpath
```
- name: workspace
persistentVolumeClaim:
claimName: app-studio-default-workspace
subPath: application-service-{{revision}}
```
2. Run tests using a `make test` 
3. Build a PR image and push to https://quay.io/repository/redhat-appstudio/pull-request-builds?tab=tags
> Build and test as part of CI 

- controllers/component_controller.go
- controllers/component_controller_test.go
Adds timestamp to subpath field of tekton workspaces configuration in the pipeline run object of initial build.
https://issues.redhat.com/browse/PLNSRVCE-53
1. Create an app and a components as usual.
2. Check, that created PipelineRun object has subpath with timestamp
> Add timestamp to component's initial build subpath

- gitops/generate.go
- gitops/generate_test.go
Fixes https://issues.redhat.com/browse/DEVHAS-70
Adds common Kubernetes labels to the generated gitops resources for each component (Deployment, Service, and Route). The full list of labels can be found here: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels. Certain labels that were not (or not yet) applicable to HAS, have been left out for the time being.
> [DEVHAS-70] Add K8s labels to gitops resources

- gitops/generate_build.go
This PR adds a new annotation ("pipelines.appstudio.openshift.io/type") which aims to unify annotations for PipelineRuns across AppStudio.
This annotation would replace, at least, "build.appstudio.openshift.io/type". Tentatively, it would also replace "build.appstudio.openshift.io/build". Both of these annotation have been replaced so this is not a breaking change.
> Add new annotation

- api/v1alpha1/component_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
- config/crd/bases/appstudio.redhat.com_components.yaml
Add a new field to the component CRD. This field will be used by the Release service to trigger releases for a given component.
> Add releaseStrategies field to component CRD

- gitops/generate.go
- gitops/generate_test.go
Fixes the warning message seen when deploying GitOps resources generated by HAS
> Use proper APIVersion for Route

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_conditions.go
- controllers/componentdetectionquery_controller_test.go
- pkg/devfile/detect_test.go
- pkg/util/util_test.go
- Cleans up old CDQ resources when they get deleted
- Also adds new `Detecting` status condition to the CDQs, as discussed earlier
- Name to be decided, so it's just a placeholder til we finalize on a proper name for the status.
- Test case for the CDQ deletion logic.
> Clean up old CDQ resources when they are requeued

- .tekton/pull-request.yaml
- .tekton/push.yaml
As PVC is created for the whole namespace and the pipelineRun is using subPath, the PVC was being full very soon, and to overcome this, as a workaround we used volumeClaimTemplate, which creates PVC for each pipelineRun.
Now, there is a [PVC-cleaner](https://github.com/redhat-appstudio/pvc-cleaner) which will delete the subPath when a pipelineRun is deleted.
This PR is to switch back to subPaths from volumeClaimTemplate.
https://issues.redhat.com/browse/PLNSRVCE-174
> update has to use PVC instead of volumeClaimTemplate

- api/v1alpha1/component_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/appstudio.redhat.com_componentdetectionqueries.yaml
- bundle/manifests/appstudio.redhat.com_components.yaml
- config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
- config/crd/bases/appstudio.redhat.com_components.yaml
Per https://issues.redhat.com/browse/HACBS-287, the `ReleaseStrategy` will be stored in the `ReleaseLink` CRD going forward
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Remove releaseStrategy field from component CRD

- controllers/component_controller.go
- controllers/component_controller_test.go
Fixes https://issues.redhat.com/browse/DEVHAS-94
Updates the Component controller logic to requeue if a Component's Application cannot be found, or is not finished reconciling.
> [DEVHAS-94] Requeue the Component when its Application can't be found

- api/v1alpha1/component_types.go
- api/v1alpha1/componentdetectionquery_types.go
- config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
- config/crd/bases/appstudio.redhat.com_components.yaml
- controllers/component_controller.go
- controllers/component_controller_test.go
- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- controllers/update.go
- controllers/update_test.go
- gitops/generate.go
- gitops/generate_test.go
- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Fixes https://issues.redhat.com/browse/DEVHAS-26
This PR implements support for (public and private) container image components in HAS. It also moves the `spec.Source.GitSecret` field to `spec.Secret` to allow both Git and Image components to reference secrets.
When a Component is created in HAS referencing a container image, like so:
```
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
name: component-example
namespace: default
spec:
application: application-example
build:
containerImage: ''
componentName: sample-component-name
resources: {}
source:
image:
containerImage: docker.io/openshift/hello-openshift
```
HAS will generate gitops resources that reference that container image and push it to the gitops repository. If a private container image needs to be used, then …
> [DEVHAS-26] feat: Support container image components

- controllers/component_controller.go
- gitops/generate.go
- gitops/generate_build.go
- gitops/generate_test.go
Moves the common storage pvc file to application level in the gitops repository
For example: https://github.com/redhat-appstudio-appdata/my-app-default-mix-climb
> Put common-storage-pvc at application-level in gitops repository

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Adds the context attribute (`appModelRepository.context`) and (`gitOpsRepository.context`) by default to the Application devfile generated by HAS. 
If no context is specified, it will default to `/`, otherwise the context value will be used.
> Add context attribute to Application devfiles by deafult

- .ci/oci-e2e-has.sh
Script to install the e2e binary and pair PR. More details about pairing PR feature can be found: https://github.com/flacatus/e2e-tests/blob/docs/docs/Installation.md#install-e2e-binary-in-openshift-ci-and-use-pairing-prs-feature
> Use e2e installation script to install e2e framework and pair PR

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
ArgoCD app created is falining on:
'rpc error: code = Unknown desc = Manifest generation error (cached): /: app path is absolute'
> fix: ArgoCD requires relative path

- config/rbac/role.yaml
- controllers/component_controller.go
- controllers/component_controller_unit_test.go
- gitops/generate.go
- gitops/generate_build.go
- gitops/generate_build_test.go
- gitops/gitops.go
- gitops/gitops_test.go
- gitops/prepare/prepare.go
- gitops/prepare/prepare_test.go
[PLNSRVCE-141](https://issues.redhat.com//browse/PLNSRVCE-141)
This is a reimplementation of #74 considering the splitting of the code into the build-service operator.
----
This PR provides a simple mechanism to allow the overriding of the Tekton bundle that will be inserted into the generated TriggerTemplate when a Component CR is created.
To do that, a configmap needs to be created in the same namespace as the Component CR:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: build-pipelines-defaults
data:
default_build_bundle: "quay.io/user/custombundle:version" 
```
In case this configmap is not available, HAS will try to search for one with the same name at the `build-templates` namespace. If no configmap is found, it will resort to the one that's currently …
> Allow the overriding of the default Tekton bundle

- gitops/generate_build.go
Feb is taken as string so it's not replaced. 'Jan' works properly.
> Fix format date, Feb is not evaluated

- .tekton/pull-request.yaml
- .tekton/push.yaml
Update the pipelineRef bundle with hacbs-core-service-templates-bundle, which is an extension of hacbs, for core services of AppStudio/HACBS, allows creating MR in infra-deployments and also add the infra-deployment update script.
> ci: add hacbs-core-service pipeline

- .ci/openshift-ci/Dockerfile
update ci docker image to go 1.17
> update ci docker image to go 1.17

- gitops/generate_build.go
This MR adds common set of labels to the PipelineRuns that are created by an event coming from webhook, making labels consistent on initial and even based builds. Also this will allow to do PipelineRuns filtering in build-service.
> Add common labels to pipeline run generated by webhook event

- .ci/oci-e2e-has.sh
* extract PR metadata that will be used to override [reference to HAS kustomize in infra-deployments](https://github.com/redhat-appstudio/infra-deployments/blob/1d623e2278aecbdf266f374e02cf3f55de62a42f/hack/preview.sh#L91)
* depends on this PR https://github.com/redhat-appstudio/infra-deployments/pull/373
> fix: override HAS kustomize config in e2e tests

- gitops/generate_build.go
- gitops/generate_build_test.go
When generating TriggerTemplate for the component, ignore git revision hash suffix in the image tag.
Also, it aligns default to `latest` to have compatible with docker behavior.
When a new version of component image is built, it is automatically put into component's spec, so the change is reflected in gitops resources and in the component's deployment in the cluster.
Before this change, image in the TriggerTemplate had the following structure: `image-$(tt.params.git-revision)`. That worked fine for the first build, but then the image became `image-sha1234` and on the next build it turns into `image-sha1234-$(tt.params.git-revision)` and so on (until max tag lengths is reached).
To fix the problem above, it's proposed to ignore git revision …
> Ignore component image commit hash in tag

- Makefile
- config/kcp-rbac/application_editor_role.yaml
- config/kcp-rbac/application_viewer_role.yaml
- config/kcp-rbac/component_editor_role.yaml
- config/kcp-rbac/component_viewer_role.yaml
- config/kcp-rbac/componentdetectionquery_editor_role.yaml
- config/kcp-rbac/componentdetectionquery_viewer_role.yaml
- config/kcp-rbac/kustomization.yaml
- config/kcp-rbac/leader_election_role.yaml
- config/kcp-rbac/leader_election_role_binding.yaml
- config/kcp-rbac/manager_webhook_patch.yaml
- config/kcp-rbac/role.yaml
- config/kcp-rbac/role_binding.yaml
- config/kcp-rbac/role_build.yaml
- config/kcp-rbac/role_spi.yaml
- config/kcp-rbac/service_account.yaml
- config/kcp-webhooks/kustomization.yaml
- config/kcp-webhooks/manager_webhook_patch.yaml
- config/kcp-webhooks/manifests.yaml
- config/kcp-webhooks/webhookcainjection_patch.yaml
- config/kcp/kustomization.yaml
- config/kcp/webhookcainjection_patch.yaml
- docs/kcp-old.md
- docs/kcp-webhooks.md
- docs/kcp.md
- hack/kcp/webhook-route.yaml
- hack/kcp/webhook-service.yaml
Related to: https://issues.redhat.com/browse/DEVHAS-102
This PR adds the following manifests for running HAS on KCP:
- `config/kcp` 
- Deploys HAS on KCP without webhooks.
- `config/kcp-webhooks`
- Enables webhooks for HAS on KCP
- **Note:** Enabling webhooks is still a bit of a manual process even with this Kustomize manifest, and the `kcp-webhooks.md` doc that I am adding **must** be followed when enabling webhooks
- `config/kcp-rbac`
- A copy of `config/rbac` with certain manifests removed that were not needed for KCP
The following docs have been modified or added
- `docs/kcp.md`
- Covers how to run KCP on a managed instance of KCP (e.g. kcp-stable or kcp-unstable)
- `docs/kcp-webhooks.md`
- Covers how to enable webhooks for HAS, _after_ installing HAS on KCP
- `docs/kcp-old.md` …
> [DEVHAS-102] Add KCP-specific manifests and docs

- controllers/component_controller.go
Fixes https://issues.redhat.com/browse/DEVHAS-116
Surfaces the full error message in the Component status condition when gitops generation fails.
> Fix GitOps generation error message

- gitops/generate_build.go
10MB is not enough to run builds. Increasing to 1GB.
Currently it works because value is overridden in https://github.com/redhat-appstudio/build-service/blob/c77a839b79d26bd1c27d0802e45fc9b558a5f1b7/controllers/component_build_controller.go#L162
> Inceasing common storage to 1GB

- controllers/component_controller.go
- controllers/component_controller_finalizer.go
- pkg/util/util.go
- pkg/util/util_test.go
Fixes https://issues.redhat.com/browse/DEVHAS-134
Adds a new util function (+ tests) for sanitizing error messages. Can expand in the future as needed. Updates the Component controller to call this function before reporting errors from the gitops library.
> [DEVHAS-134] Sanitize Git error messages

- gitops/generate_build.go
- gitops/generate_build_test.go
This PR contains a fix for Components where the default branch is other than `main` and is specified in the the Component Spec as part of the source git reference
The repository https://github.com/Apicurio/apicurio-registry uses `master` instead of main but the reference in the component is ignored when a build is created and the build fails. This PR adds a check to setthe revision into the pipeline run if it is set in the component. 
Example (note the `revision: master`) 
```
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
name: service-registry
spec:
componentName: service-registry
application: service-registry
containerImage: quay.io/jduimovich0/service-registry
source:
git:
url: https://github.com/Apicurio/apicurio-registry
revision: master
devfileUrl: …
```
> Use the Component revision

- Makefile
When running the command `make build` or `make test`, no dependencies are downloaded. Fixing the issue by replacing 'go get' to 'go install'.
> Command 'make build' not downloading dependencies.

- gitops/generate.go
- gitops/generate_build.go
- gitops/generate_test.go
- gitops/gitops.go
- gitops/testutils/testutils.go
If a namespace has two or more AppStudio applications, and one of them gets deleted, the `appstudio` volume is switched into deletion state. Such behavior causes some errors for the others components. To avoid this problem, we do not manage `appstudio` pvc via gitops, but create it from build-service operator.
> Do not add `appstudio` pvc to gitops

- controllers/component_controller.go
- gitops/gitops.go
- gitops/gitops_test.go
As we discussed before, if there is no need to support custom patches in component/base folder, we can assume all files under base folder are generated, and can be safely deleted during component (re)generation.
This PR add back the logic to blow away base folder and also it's unit tests.
> blow away base folder when generate component

- api/v1alpha1/component_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/appstudio.redhat.com_componentdetectionqueries.yaml
- bundle/manifests/appstudio.redhat.com_components.yaml
- config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
- config/crd/bases/appstudio.redhat.com_components.yaml
- config/kcp/apiexport_has.yaml
- config/kcp/apiresourceschema_has.yaml
`ReleaseStrategies` in component spec was moved in https://github.com/redhat-appstudio/application-service/pull/95
but accidentally being added back after that. removing the field
> remove ReleaseStrategies

- .github/workflows/pr.yml
KCP now requires Go 1.18 to build now, so need to update our PR workflow to use it.
> Use Go 1.18 in GitHub workflow

- gitops/generate_build.go
- gitops/generate_build_test.go
- gitops/prepare/prepare.go
- gitops/prepare/prepare_test.go
* Detect HACBS by checking if hacbs configmap exists
* When HACBS is enabled then:
- select hacbs tekton bundle
- enable PipelinesAsCode
Note: HACBS detection by configmap is temporary solution, will be
changed to detection based on APIBinding API in KCP environment.
> PLNSRVCE-624: Detect HACBS workflow

- api/v1alpha1/component_types.go
- config/crd/bases/appstudio.redhat.com_components.yaml
- config/kcp/apiexport_has.yaml
- config/kcp/apiresourceschema_has.yaml
- controllers/component_controller.go
- controllers/component_controller_test.go
- gitops/gitops.go
- gitops/gitops_test.go
- gitops/testutils/testutils.go
- pkg/util/util.go
Part 1 of https://issues.redhat.com/browse/DEVHAS-148
This PR adds a new field to the status of Component resources, `commitID`, which corresponds to the most recent commitID in the GitOps repository for that given Component. To retrieve the commitID, I added a function `GetCommitSHAFromRepo`, which calls `git rev-parse HEAD` on the given repository folder. (Note: There are multiple approaches to get the commit ID, but this approach was the most straightforward and testable). 
For the controller unit tests, which do not use 'real' GitOps repositories (which means there is no commit SHA to retrieve), I updated the mock executor that we use to return a dummy commit SHA when `git rev-parse HEAD` is called.
> [DEVHAS-148] Add GitOps commit ID to Component status

- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/applicationsnapshotenvironmentbinding_controller_test.go
- controllers/component_controller.go
- controllers/component_controller_finalizer_test.go
- controllers/component_controller_unit_test.go
- controllers/suite_test.go
- gitops/testutils/testutils.go
- go.mod
- go.sum
Fixes https://issues.redhat.com/browse/DEVHAS-148
- Adds CommitID to ASEB status
- Updates GitOps generator executor mock to trigger an error for test cases testing git commit id retrieval
- Fixes a bug retrieving the commitID for Components (wrong dir was used)
- Fixes a misc. bug in the tests causing a flake in the finalizer tests
> Add CommitID to ASEB status

- gitops/generate.go
- gitops/generate_test.go
Fixes https://issues.redhat.com/browse/DEVHAS-162
If we don't specify an empty struct for the deployment patch, the `null` selector field overwrite the existing selector in the base deployment file. If it's set to an empty struct (`{}`), then the selector specified in the base deployment will be used.
```
johncollier@jcollier-mac ~ % cd petclinic-default-assess-read/components/component-sample/overlays/staging 
johncollier@jcollier-mac staging % cat deployment-patch.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
creationTimestamp: null
name: component-sample
namespace: default
spec:
replicas: 3
selector: {}
strategy: {}
template:
metadata:
creationTimestamp: null
spec:
containers:
- env:
- name: FOO
value: BAR
image: quay.io/redhat-appstudio/user-workload:application-service-system-c …
```
> [DEVHAS-162] Make sure deployment patch selector is not null

- controllers/applicationsnapshotenvironmentbinding_controller.go
- pkg/devfile/detect.go
- pkg/devfile/devfile.go
- pkg/util/util.go
Clean up errors and warnings.  Annotated findings that do not need fixing with `#nosec` so future scans will skip over them
> Assess and fix sast-go findings from pipeline run

- .tekton/push.yaml
The config changed in infra-deployments from 'config/default' to 'config/kcp', improving regexp to match all subfolders of application-service
> infra-deployment updater: update all application-service resources

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- controllers/update.go
- controllers/update_test.go
The PR removes the kube get request to check naming conflict in existing components. Instead, it always append random 4-char string ([0-9][a-z][A-Z]) at the end to avoid conflict.
> [DEVHAS-143] always append random string at end of component name

- gitops/generate_build.go
- gitops/generate_build_test.go
Use volumeClaimTemplate instead of static PVC in the pipeline run spec returned from `DetermineBuildExecution`
[PLNSRVCE-700](https://issues.redhat.com//browse/PLNSRVCE-700)
The trigger template should use `volumeClaimTemplate`.
> PLNSRVCE-700: use volumeClaimTemplate instead of static PVC

- gitops/generate_build.go
- gitops/generate_build_test.go
Use appstudio.openshift.io/[component|application] instead of build.appstudio.openshift.io/[component|application]
Unification of labels, component and application is global identifications, it's not just for build part.
[PLNSRVCE-715](https://issues.redhat.com//browse/PLNSRVCE-715)
> PLNSRVCE-715: Unify labels to use appstudio.openshift.io/application

- gitops/generate_build.go
- gitops/generate_build_test.go
When the redhat-appstudio-pull-secret is used, this change injects
the secret into the podTemplate under the imgPullSecret field
Signed-off-by: Joe Stuart <jstuart@redhat.com>
> Tekton chains needs a pull secret to push attestations and signatures

- config/kcp-manager/kustomization.yaml
- config/kcp-rbac/kustomization.yaml
- config/kcp-rbac/leader_election_role_binding.yaml
- config/kcp-rbac/role_binding.yaml
No longer uses the default service account on KCP, as it's no longer required.
> No longer use default serviceaccount on KCP

- .tekton/push.yaml
- config/kcp/apiexport_application-service.yaml
- config/kcp/kustomization.yaml
- Create APIExport which can be reused by infra-deployments
- Use APIExport application-service by default
Infra-deployments changes related to this change -> https://github.com/redhat-appstudio/infra-deployments/pull/790
Updates infra-deployments with APIExports
> Update infra-deployments with identityHashes

- .ci/openshift-ci/Dockerfile
Need to switch to 1.18 for https://github.com/redhat-appstudio/application-service/pull/195
> Use Go 1.18 in OpenShift CI

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_conditions.go
~This PR makes sure we don't start reconciling CDQ resources on KCP until after the `kcp.dev/cluster` annotation has been added.~
Since KCP may attach a number of KCP-specific annotations and labels to the resource, this may cause conflicts when trying to update the resource:
```
2022-10-13T15:16:51.519Z    ERROR   controllers.ComponentDetectionQuery Unable to update ComponentDetectionQuery    {"ComponentDetectionQuery": "has-e2e-ndry/quarkus-component-e2e-madtwgalft", "clusterName": "test", "error": "Operation cannot be fulfilled on componentdetectionqueries.appstudio.redhat.com \"quarkus-component-e2e-madtwgalft\": the object has been modified; please apply your changes to the latest version and try again"}
```
Since we only allow CDQs …
> [DEVHAS-178] Use MergePatch to update CDQ status

- controllers/application_controller.go
- controllers/componentdetectionquery_controller.go
- pkg/github/github.go
- pkg/github/github_test.go
This PR updates the GitOps repository name generation to no longer use the Component's namespace, and instead uses a hash of the combined clusterName and namespace. 
https://issues.redhat.com/browse/DEVHAS-176
> [DEVHAS-176] Remove namespace from the GitOps repository name

- config/kcp/apiexport_application-service.yaml
This PR adds `ApplicationSnapshot` to the apiexport used for HAS in infra-deployments
Fixes https://issues.redhat.com/browse/DEVHAS-188
N/A
> [DEVHAS-188] Add missing ApplicationSnapshot permission claim

- controllers/applicationsnapshotenvironmentbinding_controller.go
- go.mod
- go.sum
- pkg/util/util.go
- pkg/util/util_test.go
Signed-off-by: Keith Chong <kykchong@redhat.com>
React to the refactoring changes made in https://github.com/redhat-developer/gitops-generator/pull/20
Refactoring and simplification of the mapping. Existing tests updated.
Existing tests pass
Refactoring only
No impact
The mapping has been simplified and unused fields from the original types are removed.  They were not referenced when generating the k8s resources.  The mapping has been renamed to a more general name,
> React to refactored structs in GitOps Generator (#2314)

- controllers/component_controller_finalizer.go
- go.mod
- go.sum
Signed-off-by: Keith Chong <kykchong@redhat.com>
Update to pull in the gitops-generator that includes.
https://github.com/redhat-developer/gitops-generator/pull/24
This pulls the latest changes to the gitops-generator except for the change for 
https://github.com/redhat-developer/gitops-generator/pull/28
@kim-tsao FYI
No HAS issue/story has been opened
Just refactoring and pulling in the updated generator module.
I ran make test, and they all pass.  Existing tests sufficient.
N/A
N/A
Just run the tests locally.
> Update to use GitRemoveComponent API (#2398)

- .github/workflows/kcp-test.yml
- .gitignore
- hack/kcp/test-has.sh
This PR adds a basic GitHub workflow to test HAS on KCP. Since we cannot access GitHub secrets on workflows (which most HAS functionality requires) from PRs and to avoid duplication with the existing KCP e2e tests, this workflow runs just some basic sniff tests:
1. Sets up Minikube and KCP, and creates a SyncTarget pointing to the Minikube cluster
2. Deploys HAS using `make deploy-kcp`
3. Creates a CDQ resource and validates it succeeds
https://issues.redhat.com/projects/DEVHAS/issues/DEVHAS-129
GitHub workflow passes
> [DEVHAS-129] Add basic sniff test for HAS on KCP

- docs/appstudio-kcp.md
- hack/appstudio-kcp/api-binding.yaml
- hack/appstudio-kcp/has-binding.yaml
- hack/appstudio-kcp/spi-binding.yaml
Adds apibindings under `hack/` to allow for testing HAS in staging, along with supporting documentation.
N/A
The documentation and bindings allow HAS to be tested on staging on CPS.
> Add apibindings for testing staging on KCP

- controllers/component_controller.go
- controllers/component_controller_unit_test.go
- controllers/suite_test.go
- gitops/prepare/prepare.go
- gitops/prepare/prepare_test.go
- main.go
Removes KCP client that can access the workspace where the operator is deployed.
Changes behavior of gitops prepare, so now everything is taken from current cluster (KCP workspace)
Removing KCP epic
> Delete local client

- config/default/kustomization.yaml
Removes the entry in the default kustomization.yaml that installs the application-api CRDs. The CRDs are installed via their own component (`application-api`) in infra-deployments, and our `make install` target also takes care of their installation for development. 
We do not want to duplicate the installation of the CRDs to avoid any potential conflicts.
https://issues.redhat.com/browse/DEVHAS-200
> [DEVHAS-200] Remove duplicate application-api crd from default kustomize

- .tekton/pull-request.yaml
- .tekton/push.yaml
volumeClaimTemplate provides PVC cleanup out-of-box. Update path to new non-kcp infra-deployments main.
> tekton-ci: Use volumeClaimTemplate instead of static PVC, update path

- controllers/suite_test.go
- go.mod
- go.sum
Updates the application-api package version to latest, which pulls in the webhook validation for the `spec.displayName` field in Applications
https://issues.redhat.com/projects/DEVHAS/issues/DEVHAS-206
> Pull in latest application-api changes

- controllers/application_controller_finalizer_test.go
- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/applicationsnapshotenvironmentbinding_controller_test.go
- controllers/component_controller.go
- controllers/component_controller_unit_test.go
- controllers/suite_test.go
- go.mod
- go.sum
- main.go
- pkg/github/github.go
- pkg/github/github_test.go
- pkg/github/mock.go
Updates the logic in the Component and ASEB controllers to use go-github to get the Commit ID instead of using the gitops generator library. This will allow us to separate out the gitops resource generation to a job, without having to report back the commit ID from it somehow.
Part of https://issues.redhat.com/projects/DEVHAS/issues/DEVHAS-53?filter=allopenissues
Commit ID is added and present in the status of Component and ASEB resources (as was before).
> [DEVHAS-53] Use go-github to get commit ID

- controllers/component_controller.go
When component provides devfileUrl and dockerfileUrl then prefer devfileUrl. Otherwise devfileUrl is completely ignored - metadata are lost.
We need to pass language metadata from devfile to status so that build-service can properly select pipeline - [PLNSRVCE-799](https://issues.redhat.com//browse/PLNSRVCE-799)
> fix: evaluate devfile before dockerfile

- codecov.yml
- controllers/componentdetectionquery_controller_conditions.go
- controllers/componentdetectionquery_controller_conditions_test.go
- controllers/update.go
- controllers/update_test.go
- gitops/generate_build.go
- gitops/generate_test.go
- license_header.txt
This PR updates the logic for the component name generation that CDQs use to properly handle Git repositories that end with a tailing forward slash (e.g. https://github.com/devfile-samples/devfile-sample-java-springboot-basic/). Previously, an empty string would be returned, instead of the Git repository name, leading to an invalid Component name like `-ohu7`.  With this change, we now properly handle URLs with a tailing slash. Furthermore, if `sanitizeComponentName` is called with an empty name, we use the `gofakeit` package to generate an empty string. 
Additionally, I've updated the logic setting the status on CDQs, where if the status update fails, we try again by only updating the status condition. …
> [DEVHAS-213] Properly handle CDQs for repo URL with tailing '/'

- gitops/prepare/prepare.go
- gitops/prepare/prepare_test.go
Change the namespace from component's to the global where `pipelines-as-code-secret` is searched for.
This allows to correctly detect if GitHub PaC Application is used and crerate PaC Repository CR correctly in GitOps repository.
https://issues.redhat.com/browse/PLNSRVCE-983
Test build via PaC GitHub Application after ArgoCD syncs gitops repository to the cluster.
> Fix PaC Repository CR generation in gitops

- controllers/component_controller.go
Removing eventlistener route handling since tektontriggers and eventlisteners are not used anymore.
> Event listeners removed, should not not be handled

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- pkg/devfile/detect.go
- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Alternative to https://github.com/redhat-appstudio/application-service/pull/239. Instead of creating a new map to store the context/local path of the devfile, this PR updates `devfile.search()` to properly set the `devfilesURLMap` when devfiles are detected locally in a multi-component repository. 
https://issues.redhat.com/browse/DEVHAS-225
> [DEVHAS-225] Properly set devfileURL in CDQs for multi-component repos

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- pkg/devfile/detect_mock.go
This PR updates the logic in the CDQ controller that sets DockerfileURL links, so that it only overrides the DockerfileURL link to the source repository if the given context/path is local. If the given path is absolute (i.e. a fully qualified address), then we no longer override it.
https://issues.redhat.com/browse/DEVHAS-226
> [DEVHAS-226] Only override DockerfileURL if its path is local and not absolute

- gitops/prepare/prepare.go
- gitops/prepare/prepare_test.go
Remove code for registrysecret which is not used anymore. Registry secrets should be linked to serviceaccount instead.
[PLNSRVCE-1019](https://issues.redhat.com//browse/PLNSRVCE-1019)
> PLNSRVCE-1019: build - remove registry-secret

- controllers/application_controller.go
- controllers/application_controller_test.go
This PR updates the GitOps repository name generation to use the Application's`metadata.name` instead of `spec.displayName`. Existing Applications with gitops repositories based on display names will not be affected.
Fixes https://issues.redhat.com/browse/DEVHAS-231
GitOps repo names include the metadata.name field
> - Open new test/doc issues
> - Check each criteria if:
>  - There is a separate tracking issue. Add the issue link under the criteria
>  **or**
>  - test/doc updates are made as part of this PR
> -  If unchecked, explain why it's not needed
-->
> [DEVHAS-231] Use metadata.Name for GitOps repository

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- controllers/update.go
- pkg/devfile/detect_test.go
- pkg/devfile/devfile_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Updates the componentStub returned by the CDQ to include the Git revision if `GitSource.revision` was set in the CDQ's spec. 
https://issues.redhat.com/browse/DEVHAS-223
Tests pass and ComponentStub now includes the proper Git revision if set in the CDQ spec.
> [DEVHAS-223] Set revision in componentStub if set in CDQ's spec

- gitops/generate_build.go
- gitops/generate_build_test.go
Ending slash is causing issue in Pipelines-as-code, reported as SRVKP-2808.
> STONEBLD-687: repository without ending '/'

- pkg/devfile/detect.go
- pkg/devfile/detect_test.go
When `recognizer.SelectDevFileFromTypes` returns an error, it also returns `-1` for its index return value, which is not a valid index. Since we not checking the error and just directly returning the index within the DevfileTypes array and error, this could lead to a panic when index == -1. 
This PR simply adds an err check and returns appropriately before we attempt to access the index within the DevfileTypes array.
https://issues.redhat.com/browse/DEVHAS-245
> [DEVHAS-245] Prevent a panic from occurring when SelectDevfileFromTypes returns an error

- pkg/util/util.go
- pkg/util/util_test.go
Updates the `GetMappedGitOpsComponent` function to set default values for the CPU & Memory requests/limits that we pass into the GItOps Generator, if those fields are unset in the Component spec.
https://issues.redhat.com/browse/DEVHAS-224
GitOps resources are generated with default values for CPU & Memory request/limits from now on.
> - Open new test/doc issues
> - Check each criteria if:
>  - There is a separate tracking issue. Add the issue link under the criteria
>  **or**
>  - test/doc updates are made as part of this PR
> -  If unchecked, explain why it's not needed
-->
> [DEVHAS-224] Provide default cpu/memory request and limits if unset in Component spec

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
This PR fix the issue that if the resource attribute is unset, the `attributes.GetString` returns "0" case. 
in the empty checks, ignore the `0` for all limits & requests, as setting to 0 does not make sense anyways. 
Tested the issue should have been fix: 
previously without the change: https://github.com/yangcao77/stephanie-app-yangcao-take-sit/blob/3ee8a35ad25cd670374784dc3764fe676b0e760b/components/devfile-sample-go-basic2/base/deployment.yaml#L41-L48
with the change:  https://github.com/yangcao77/stephanie-app-yangcao-take-sit/blob/main/components/devfile-sample-go-basic2/base/deployment.yaml#L42-L46
https://issues.redhat.com/browse/DEVHAS-255
> [DEVHAS-255]update the attribute check to bypass 0 limit/request

- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/applicationsnapshotenvironmentbinding_controller_conditions.go
Changes the logic to update the SEB status from `Status().Update()` to `Status().Patch()`
> Use Patch() to update SEB status

- .tekton/push.yaml
Fixes the path in `.tekton/push.yaml` for the HAS component in infra-deployments from `components/has/kustomization.yaml` to `components/has/base/kustomization.yaml`
[DEVHAS-268](https://issues.redhat.com/browse/DEVHAS-268)
> [DEVHAS-268] Fix path to HAS component in infra-deployments

- controllers/component_controller.go
Avoid deployment of Repository CR on external cluster by disabling the .tekton folder creation.
> STONEBLD-789: Disable .tekton gitops dir creation

- go.mod
- go.sum
- main.go
Adds go-github-ratelimit to HAS. Configures it with a default single rate limit timeout of 1 minute, the remaining optional configurations have not been set for the time being.
https://issues.redhat.com/browse/DEVHAS-260
> [DEVHAS-260] Add go-github-ratelimit to HAS

- controllers/application_controller.go
- controllers/application_controller_finalizer.go
- controllers/application_controller_finalizer_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
This PR updates the logic in the Component controller for handling scenarios where the Application isn't reconciled before the Component is.
Previously, if a Component's associated Application resource was not finished reconciling, or had an error state associated with it, we would return an error message in the Component. However, in scenarios where the the Component and Application are created together, it's not ideal to immediately display that error message.
With this PR, when the Component controller encounters that error, we instead add a counter annotation to the Component. If the error occurs 5 consecutive times, we then return the original error in the Component status. Otherwise, if the error goes away, we don't display it.
https://issues.redhat.com/browse/DEVHAS-264
> [DEVHAS-264] Don't immediately display Application not ready error

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
Removes the code that would change the local dockerfile URI to be absolute for Dockerfile components. Since we no longer want to provide an absolute URI in this component, this can be removed, and we can fall back on returning a local URI.
https://issues.redhat.com/browse/DEVHAS-274
> [DEVHAS-274] Always return local Dockerfile URI if Dockerfile present in repository

- controllers/update.go
- controllers/update_test.go
This PR fixes the cdq default name generation rule. now starting with a numeric character is not accepted. 
The `sanitizeComponentName` will add a `comp-` prefix if the component name starts with a number. 
```
Spec:
Git:
URL:  https://github.com/hacbs-release/fbc-test
Status:
Component Detected:
comp-413-fbc-test-8iki:
Component Stub:
Application:     insert-application-name
Component Name:  comp-413-fbc-test-8iki
Replicas:        1
```
https://issues.redhat.com/browse/DEVHAS-278
> [DEVHAS-278] fix the cdq default name generation rule

- README.md
- config/manager/manager.yaml
- controllers/application_controller.go
- controllers/application_controller_finalizer.go
- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/component_controller.go
- controllers/component_controller_finalizer.go
- controllers/component_controller_unit_test.go
- controllers/componentdetectionquery_controller.go
- controllers/suite_test.go
- main.go
- pkg/github/github.go
- pkg/github/github_test.go
- pkg/github/token.go
- pkg/github/token_mock.go
- pkg/github/token_test.go
- Allow HAS to support using an arbitrary number of GitHub tokens for its Git operations.
- A new environment variable, `GITHUB_TOKEN_LIST`, has been created for this. It can be set to a comma separated list of GitHub tokens. E.g. `GITHUB_TOKEN_LIST=some_token1,some_token2,some_token3`
- `GITHUB_AUTH_TOKEN` remains in place in HAS, but I've removed its mention from the readme
- Moves Go-GitHub client initialization from `main.go` to each controller's `Reconcile()` function. When a client is initialized, a GitHub token will be randomly chosen, from the ones available to HAS.
- the `GitHubToken` interface (which both `GitHubTokenClient` and `MockGitHubTokenClient` implement) provides a function for handling this.
- Each controller's reconciler struct will have access to this …
> [DEVHAS-290] Support multiple tokens & Initialize go-github during reconcile

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
This PR trims leading and trailing spaces in repo URL to ensure the URL set in component spec is a valid one, and will bypass the web hook check. 
https://issues.redhat.com/browse/DEVHAS-275
> [DEVHAS-275]trim leading and trailing spaces in repo URL

- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- controllers/update.go
- controllers/update_test.go
- pkg/devfile/detect.go
- pkg/devfile/detect_mock.go
- pkg/devfile/detect_test.go
- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Updates our code in CDQs to retrieve the ports when we use alizer to detect Components. If ports are present for the detected component(s) they will be set in the Component stub. If no ports are detected, we will fall back on the ports present in the devfile.
https://issues.redhat.com/browse/DEVHAS-207
> [DEVHAS-207] Detect ports in Component when running alizer

- controllers/componentdetectionquery_controller_test.go
- controllers/update.go
In https://github.com/redhat-appstudio/application-service/pull/250, we addressed the bug where the source revision for Components was not being returned in the CDQ status. However, it seems that we were only setting the revision for Components with a Devfile present. For Dockerfile-only components, the revision was not being set, as the revision needed to be set in a different part of code.
This PR updates the CDQ logic so that the revision is also returned for Dockerfile components, and updates test cases to ensure this scenario is covered.
https://issues.redhat.com/browse/DEVHAS-223
> [DEVHAS-223 Redux] Ensure revision is set for Dockerfile-only components

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
This PR updates the `GetResourceFromDevfile()` function to trim the names of the route that retrieve from endpoints in a Component's devfile. Previously we were only trimming the route name when we generate resources _not_ from a devfile (e.g. from scratch). 
As recommended earlier, the route name should be less than 30 characters, and we reserve the last 4 characters to append 4 random characters for uniqueness.
https://issues.redhat.com/browse/STONEBUGS-108
> [STONEBUGS-108] Trim route names from the devfile parser

- README.md
- controllers/component_controller.go
- controllers/suite_test.go
- gitops/generate_build.go
- gitops/generate_test.go
- main.go
Removes code that sets default value into `ContainerImage` field.
It should be done by user or image controller should provide annotation with the created image repository
[STONEBLD-818](https://issues.redhat.com/browse/STONEBLD-818)
[HAC-3275](https://issues.redhat.com/browse/HAC-3275)
> [STONEBLD-818] Do not set default component image repository

- go.mod
- go.sum
This PR gets latest devfile/library, which the [change](https://github.com/devfile/library/pull/171) to fix the kube inlined type conversion panic
https://issues.redhat.com/browse/RHTAPBUGS-113
> [RHTAPBUGS-113] pull in latest library change to fix the panic

- config/monitoring/grafana-dashboards/has-gitops-repo-metrics.json
- config/prometheus/monitor.yaml
- With the recent changes in the monitoring stack, components now have to store Service Monitors in their own repo based on this [dummy template](https://github.com/redhat-appstudio/infra-deployments/blob/main/components/monitoring/prometheus/development/dummy-service-service-monitor.yaml).
- Changes were also made in the grafana dashboard to remove an invalid DS
https://issues.redhat.com/browse/DEVHAS-272
> [DEVHAS-272] Add ServiceMonitor to HAS repo and update grafana dashboard 

- config/prometheus/monitor.yaml
Infra deployments PR is failing due to kustomize error: https://github.com/redhat-appstudio/infra-deployments/pull/1733
The problem is due to a cluster role being defined twice; once in the rbac/auth_proxy_client_clusterrole.yaml and another in the monitor.yaml.  Fix was to remove the one in the monitor.yaml. and clean up the names for other CRs.  Ran kustomize on the local changes and was able to get past the errors
https://issues.redhat.com/browse/DEVHAS-272
> [DEVHAS-272] updating monitor to  fix kustomize error

- controllers/application_controller.go
- controllers/application_controller_finalizer.go
- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/component_controller.go
- controllers/componentdetectionquery_controller.go
- pkg/github/github.go
- pkg/github/github_test.go
- pkg/github/token.go
- pkg/github/token_test.go
The secondary rate limit callback function we use can potentially panic if the Go-GitHub client name is not set in the context before the (rate limited) request is made. This PR takes the following steps to avoid that:
- The Go-GitHub client name is added to the context as soon as we initialize the Go-GitHub client
- nil pointer checks for when the Go-GitHub client is either unset or points to a non-existent client
- There's nothing we can do when its nil, so logging and returning is preferable to panicking.
- Updated test cases to ensure that we don't panic in these scenarios
> Don't allow secondary rate limit callback to panic

- config/monitoring/kustomization.yaml
This will cause an update to the Dashboard CR that will get reconciled by the Grafana operator.
> chore: Regenerate dashboard CM name

- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/applicationsnapshotenvironmentbinding_controller_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
- gitops/generate_mock.go
Avoids using the `GetLatestCommitSHAFromRepository` since that can incur rate limiting penalties.  We'll use the gitops generator method, `GetCommitIDFromRepo` instead which makes the equivalent calls using the git cli
https://issues.redhat.com/browse/DEVHAS-355
> [DEVHAS-355] rate limit improvements - switch to using GetCommitIDFromRepo

- controllers/applicationsnapshotenvironmentbinding_controller.go
When a component repo like https://github.com/psturc-org/hacbs-test-project has a devfile that does not have a devfile endpoint nor does it have an ingress/route resource in the outerloop YAML file, then the gitops generator library should generate an ingress/route based on the component.spec.targetport property..
Since the generation of ingress/route has moved from base to overlays, we need to pass the target port in the SEB controller to the Gitops generator library during resource generation.
https://issues.redhat.com/browse/DEVHAS-329
> Pass in Target Port to Gitops Generator Library for SEB controller

- controllers/component_controller_conditions.go
This PR use `retryOnConflict` as suggested by https://github.com/kubernetes-sigs/controller-runtime/issues/1748#issuecomment-994512902
The component status update cannot simply use patch, as it may lost previous gitops created status.
https://issues.redhat.com/browse/RHTAPBUGS-267
> [RHTAPBUGS-267] use retry  on conflict to update the status

- pkg/github/github.go
- pkg/github/mock.go
- pkg/github/token.go
- pkg/github/token_mock.go
- pkg/github/token_test.go
- pkg/metrics/metrics.go
- Changes the rate limiting metrics to a gauge so counter can be decremented
- Introduces a PrimaryRateLimited boolean flag in the  GitHubClient type to track when a token has been near rate limited for the purpose of incrementing and decrementing the counter
- Updated the unit tests
https://issues.redhat.com/browse/DEVHAS-376
> [DEVHAS-376] rework rate limiting metrics

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Prevents HAS from panicking when it parses Component routes that have a nil `spec.Port`.
https://issues.redhat.com/browse/DEVHAS-381
> [DEVHAS-381] Don't panic when route's spec.Port is nil

- README.md
Provides instructions for installing the pact tools for the tests, otherwise the controller tests don't run.
> Add instructions for installing pact for tests

- config/monitoring/grafana-dashboards/has-rate-limiting-metrics.json
-    Added an Overall Git CLI Operations chart, similar to the one for Overall Rate Limiting operations
-    Updated the Token Pool Metrics chart queries to use token_pool_gauge
-    Updated query labels to have the format controller_operation instead of operation so it's clear which operation is called by which controller
-    Updated all queries to eliminate duplicate labels.  Since HAS has 3 pods, we could see 3 occurrences of the same label  depending on which pod has been active.  In order to ensure labels were unique, I had to change the queries to follow the format sum(query) by (operation or tokenName)
https://issues.redhat.com/browse/DEVHAS-374
> [DEVHAS-374] update HAS rate limiting metrics dashboard

- Makefile
- controllers/application_pact_test.go
Separate unit and pact test runs during local development to make the debugging simpler.
https://issues.redhat.com/browse/HAC-4269
To test those changes, run `make test` locally and see first running the unit test suite and then the Pact test suite.
> Update local test execution flow.

- controllers/component_controller.go
- controllers/componentdetectionquery_controller.go
- pkg/util/ioutils/ioutils.go
- pkg/util/ioutils/ioutils_test.go
This PR ensures that HAS properly cleans up git repositories that it clones, when HAS encounters an error, before it usually cleans up the Git repository. 
https://issues.redhat.com/browse/RHTAPBUGS-442
> [RHTAPBUGS-442] Properly clean up cloned repositories in error states

- controllers/applicationsnapshotenvironmentbinding_controller.go
This PR ensures that the SEB controller always updates the necessary status fields of the resource during each reconcile. This will ensure that status fields like the commit ID are kept up to date with what's generated in the gitops repository overlays.
https://issues.redhat.com/browse/RHTAPBUGS-462
https://issues.redhat.com/browse/RHTAPBUGS-322
> [RHTAPBUGS-462] Always update the SEB status

- controllers/applicationsnapshotenvironmentbinding_controller.go
Changes how we update the SEB status during reconciles to ensure the route name is always persisted. If we can do so without breaking other components, it would be best to change the `BindingComponent` array in the status to a map later on. 
https://issues.redhat.com/browse/RHTAPBUGS-322
> [RHTAPBUGS-322] Properly update SEB status

- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/component_controller_finalizer.go
- pkg/util/ioutils/ioutils.go
- pkg/util/ioutils/ioutils_test.go
This PR fixes some leftover git clones that were not being cleaned up when an error occurred, in the Component finalizer and SEB controller.
https://issues.redhat.com/browse/RHTAPBUGS-442
> [RHTAPBUGS-442 Redux] Ensure gitops repository is cleaned up in error states

- controllers/componentdetectionquery_controller_test.go
- pkg/devfile/detect.go
- pkg/devfile/devfile.go
Test for [RHTAPBUGS-418](https://issues.redhat.com//browse/RHTAPBUGS-418)
Test for an issue I saw in the UI where importing a project with multiple components and a context path set results in the context path going missing.
I could not get this test to run locally as all the detection tests are timing out for me.
https://issues.redhat.com/browse/RHTAPBUGS-418
> [RHTAPBUGS-418]multiple components with context path

- cdq-analysis/pkg/componentdetectionquery.go
- cdq-analysis/pkg/componentdetectionquery_test.go
- cdq-analysis/pkg/util.go
- cdq-analysis/pkg/util_test.go
- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
This PR updates branch detection in CDQs, so that when we clone git repositories, we do branch detection based off of the cloned repository, rather than via the GitHub API. In cases where we don't have access to the cloned Git repo, we still use GitHub API for branch detection.
https://issues.redhat.com/browse/DEVHAS-407
> [DEVHAS-407] Detect branch from cloned repo

- .tekton/pull-request.yaml
- .tekton/push.yaml
Updates the tekton pipelineref.
Making the same changes as https://github.com/redhat-appstudio/release-service/pull/231
N/A
Pipeline run should pass
> Update tekton pipelineref

- .github/workflows/codecov.yml
Updates the go version on code coverage report on push event
Failure log at https://github.com/redhat-appstudio/application-service/actions/runs/5670376614/job/15365145453 for example
N/A
Tested on my local branch at https://github.com/maysunfaisal/application-service/commit/d8e8205d19ec3d88624b225350d501f70694126e and it doesnt complain about go version
> Update go version on code coverage report

- .tekton/push.yaml
Update Grafana dashboard path after change in `infra-deployments`
> chore: Update Grafana dashboard path

- controllers/component_controller.go
- controllers/component_controller_finalizer.go
When deleting a component currently the Application will not be updated if the gitops deletion fails.
fixes [RHTAPBUGS-503](https://issues.redhat.com//browse/RHTAPBUGS-503)
Currently the finalizer for the component cleans up gitops and removes the component from the application devfile, however if the gitops fails the application is not updated.
Note that I am not 100% sure that this is the correct behavior, but it seems to make sense.
https://issues.redhat.com/browse/RHTAPBUGS-503
> fix: update the application even if gitop fails

- cdq-analysis/pkg/detect.go
- cdq-analysis/pkg/devfile.go
- controllers/componentdetectionquery_controller_test.go
- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
This PR adds `dockerfile` as an alternate name for `Dockerfile`
also added unit test for it, and update existing test repo for the controller tests. 
https://issues.redhat.com/browse/DEVHAS-418
> [DEVHAS-418]add dockerfile as an alternate name for Dockerfile

- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
This PR addresses the errors found by [kube-linter](https://github.com/stackrox/kube-linter):
- Adds CPU and Memory requests and limits to the rbac proxy container
- Enables readOnlyRootFilesystem for both containers (HAS and rbac proxy)
- Adds an empty dir volume for the /tmp directory for HAS to be able to write to
https://issues.redhat.com/browse/DEVHAS-453
1. Download Kube-Linter from https://github.com/stackrox/kube-linter
2. cd into `config/default`
3. Run `kustomize build . > mainfests.yaml`
4. Run `kube-linter lint manifests.yaml`. You should see:
```
KubeLinter development
No lint errors found!
```
> [DEVHAS-453] Fix Kube-Linter errors

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Provides a Service Port name if there is more than one Service Port. The API says Name is mandatory is there is more than 1.
https://issues.redhat.com/browse/RHTAPBUGS-433
Create a Component, SEB, Snapshot, Environment. Ensure the Gitops Repo service.yaml has two service ports and both of them have names. Apply it in your OpenShift project and access the route.
Example of the Gitops Repo for providing Service Port Name https://github.com/maysunfaisal/application-sample-lK5Sb-borrow-place/blob/main/components/component-sample/base/service.yaml#L13-L20
> Provide a Service Port Name

- controllers/application_controller.go
- controllers/application_controller_finalizer_test.go
- pkg/metrics/metrics.go
Adds a metric for tracking successful and failed application deletions in HAS.
https://issues.redhat.com/browse/DEVHAS-452
> Add metric for Application deletion

- cdq-analysis/main.go
- main.go
`rest.InClusterConfig()` only works when running in a Kubernetes pod, it won't work if you're running HAS locally. To work around that, if `rest.InClusterConfig()` fails, we should retrieve the Kubeconfig locally, first from the `KUBECONFIG` env var, then from `~/.kube/config` if that fails.
> Fix restconfig retrieval - don't get inclusterconfig when local

- cdq-analysis/pkg/componentdetectionquery.go
- cdq-analysis/pkg/devfile.go
- cdq-analysis/pkg/devfile_test.go
- cdq-analysis/pkg/util.go
- cdq-analysis/pkg/util_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
- controllers/componentdetectionquery_controller.go
- docs/private-git-repos.md
- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
- pkg/util/util.go
- pkg/util/util_test.go
- Adds in private DevfileURL support for Component
- Adds in private link support for Devfiles in CDQ
https://issues.redhat.com/browse/DEVHAS-444
- Pass in the DevfileURL:
```yaml
source:
git:
context: ./
devfileUrl: https://raw.githubusercontent.com/maysunfaisal/devfile-sample-go-basic-private/main/devfile.yaml
revision: main
url: https://github.com/maysunfaisal/devfile-sample-go-basic-dockerfile-empty-private
secret: token-secret
```
- Create a Dockerfile only Component:
```yaml
source:
git:
context: ./
dockerfileUrl: docker/Dockerfile
revision: main
url: https://github.com/maysunfaisal/devfile-sample-go-basic-dockerfile-only-private
secret: token-secret
```
```yaml
Private Repo NOTES
Component:
source:
git:
context: ./
revision: main
url: …
```
> Add support for private DevfileURL in Component

- controllers/component_controller.go
This PR set a more user friendly error message for git push protection error. 
before this change, the message was too long and hard to read, also exposed the unblock-secret URL to the end user
```
Last Transition Time:  2023-10-23T21:57:49Z
Message:               Component updated failed: Unable to generate gitops resources for component application-service-system/devfile-sample-go-basic3: failed to push remote to repository "https://<TOKEN>@github.com/redhat-appstudio-appdata/application-sample2-2Ej_G-comply-travel" "remote: error: GH013: Repository rule violations found for refs/heads/main.        \nremote: Review all repository rules at http://github.com/redhat-appstudio-appdata/application-sample2-2Ej_G-comply-travel/rules?ref=refs%2Fheads%2Fmain        \nremote: \nremote: - GITHUB …
```
> [DEVHAS-514] push protection error

- controllers/webhooks/application_webhook.go
- controllers/webhooks/component_webhook.go
- controllers/webhooks/component_webhook_test.go
- controllers/webhooks/component_webhook_unit_test.go
- controllers/webhooks/webhook_suite_test.go
- go.mod
- go.sum
This PR adds changes to the Component's validating webhook to handle the `build-nudges-ref` field:
- If any nudged components belong to a different application, an error is returned and the create/update operation is blocked
- If any nudged components refer to the nudging component, either directly or indirectly, an error is returned and the operation is blocked
This PR also adds back the stub `Default()` functions for the Application and Component webhooks, as they were accidentally removed when migrating the webhooks from application-api. These functions will be needed to implement mutating webhooks as part of [DEVHAS-529](https://issues.redhat.com/browse/DEVHAS-529)
https://issues.redhat.com/browse/DEVHAS-528
N/A
N/A
> [DEVHAS-528] Add validating webhook for build-nudges-ref

- controllers/applicationsnapshotenvironmentbinding_controller.go
- controllers/update.go
Similarly as https://github.com/redhat-appstudio/application-service/pull/404
update the push protection error message for SEB controller, and also update the log message to not logging the ENV values to avoid potential secret leak in log. 
https://issues.redhat.com/browse/DEVHAS-514
> [DEVHAS-514]update SEB with the proper error message set

- cdq-analysis/pkg/componentdetectionquery.go
- cdq-analysis/pkg/componentdetectionquery_test.go
This PR move the logic of removing clonepath to beginning of `SendBackDetectionResult`, ensure the clonepath is cleaned if execute with go module when CDQ is done, regardless of error or success case. 
https://issues.redhat.com/browse/DEVHAS-549
> [DEVHAS-549]remove clonepath after cdq is done

- controllers/webhooks/component_webhook.go
- controllers/webhooks/component_webhook_test.go
- controllers/webhooks/component_webhook_unit_test.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR updates the Component webhooks to update the nudged Components' `status.BuildNudgedBy` list whenever a nudging Component references it in their `spec.BuildNudgesRef` list.
https://issues.redhat.com/browse/DEVHAS-529
> [DEVHAS-529] Update webhook to set nudged component's status when buildNudgesRef is set

- codecov.yml
Those files are test only, and shouldn't be included in coverage calculations
> Update codecov ignore list - ignore token mock and contract test files

- cdq-analysis/main.go
- cdq-analysis/pkg/componentdetectionquery.go
- cdq-analysis/pkg/componentdetectionquery_test.go
- cdq-analysis/pkg/detect.go
- cdq-analysis/pkg/detect_test.go
- cdq-analysis/pkg/devfile.go
- cdq-analysis/pkg/devfile_test.go
- cdq-analysis/pkg/mock.go
- codecov.yml
- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
- controllers/start_test_env.go
- controllers/update.go
- controllers/update_test.go
- main.go
- Introduces CDQUtil interface to abstract out CDQ logic which utilizes a git token, so that we can mock valid cases for tests with a private repo
- Remove unnecessary token usage when invoking devfile/library because we dont need a token to read byte strings
- Adds controller tests out lined in https://issues.redhat.com/browse/DEVHAS-490
https://issues.redhat.com/browse/DEVHAS-490
Run the tests `make test`
> [DEVHAS-490] Mocking CDQ Util for Private Repo Testing

- controllers/application_controller.go
- Updates the finalize logging to properly log the finalize error message
- Updates the status updates in the finalizer to retry on conflict
https://issues.redhat.com/browse/DEVHAS-547
> Fix finalize logging

- controllers/application_controller.go
Retry blocks need to include a "get" in them, so this PR updates the retry blocks added in https://github.com/redhat-appstudio/application-service/pull/417 to include Get API calls.
https://issues.redhat.com/browse/DEVHAS-547
> Get application in retry blocks

- .github/workflows/codecov.yml
- `make test` ensures the necessary envtest binaries are downloaded before running the tests so it needs to be used instead.
> Run make test on codecov upload

- pkg/devfile/devfile.go
- pkg/devfile/devfile_test.go
Removes the if statement that was used to set the replica field in the deployment spec since it should always be set to a value.   If field is unset, it should have a default value of 0.  
https://issues.redhat.com/browse/RHTAPBUGS-12
- [X ] Unit/Functional tests
Updated the unit tests to include the expected component attributes values for `deployment/replicas`
Manually tested:
1.  Built the HAS image and deployed on a local cluster.  Created a token with read and write permissions to write into a test org
2. Deployed the sample [Application](https://github.com/redhat-appstudio/application-service/blob/main/config/samples/application/app.yaml) and [Component](https://github.com/redhat-appstudio/application-service/blob/main/config/samples/component/component-basic.yaml).  Verified the …
> Fix deployment spec when replica set to 0

- .gitignore
- cdq-analysis/go.mod
- cdq-analysis/go.sum
- cdq-analysis/pkg/devfile_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
- controllers/start_test_env.go
- go.mod
- go.sum
- pkg/devfile/devfile.go
- Adds in tests for Component Devfile with Private Parent references
https://issues.redhat.com/browse/DEVHAS-492
Tests should pass
> [DEVHAS-492] Test for Component Devfile with Private Parent references

- controllers/component_controller_test.go
Adds in a couple of SPI FCR tests for the Component controller:
- Ensure SPI FCR has an owner reference tied to its associated Component
- Cant test SPI FCR deletion because the Kube client created from a test config env does not process owner ref deletions
- Ensure SPI FCR is persisted even if its associated Component is in an error state
https://issues.redhat.com/browse/DEVHAS-553
Tests should pass
> [DEVHAS-553] Add SPI FCR test checks for Component controller

- controllers/component_controller.go
Simple fix for the error log of the gitops repo update failure. The code didn't include the `fmt.Sprintf()` function and as a result inside the log we would only see the `%v` variables as they are and not their content. After adding `fmt.Sprintf()` this is fixed.
fixes https://issues.redhat.com/browse/RHTAPBUGS-1016
> Fix error log format

- controllers/applicationsnapshotenvironmentbinding_controller_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
- controllers/componentdetectionquery_controller_test.go
- go.mod
- go.sum
- pkg/devfile/errors.go
- Filters out the user errors in a devfile so that the prometheus metrics reflect a proper state
- Adds new test case to test the prometheus metric
https://issues.redhat.com/browse/DEVHAS-580
Test with updated metrics should pass
> Filter out user devfile errors

- controllers/webhooks/component_webhook.go
- controllers/webhooks/component_webhook_test.go
- controllers/webhooks/component_webhook_unit_test.go
In order to enable improved organization of Components and Applications, we want to loosen the requirement that all nudging happens within the same Application. Therefore we no longer need to run webhook validation to adhere to this constraint.
issues.redhat.com/browse/DEVHAS-593
> Enable cross-Application nudging

- cdq-analysis/pkg/componentdetectionquery_test.go
- cdq-analysis/pkg/detect_test.go
- cdq-analysis/pkg/devfile_test.go
- cdq-analysis/pkg/util_test.go
- config/samples/application/app-existing-repos.yaml
- controllers/component_controller_test.go
- controllers/componentdetectionquery_controller_test.go
- controllers/update_test.go
- docs/private-git-repos.md
- pkg/devfile/devfile_test.go
- pkg/util/util_test.go
Removes the personal links from the HAS tests
https://issues.redhat.com/browse/DEVHAS-468
tests should pass
> Remove personal links from HAS tests

- config/manager/manager.yaml
Adds in the container port to the manager container because the kube linter from stackrox was complaining about it:
```
Error: found 2 lint errors
/home/runner/work/application-service/application-service/.kube-linter/manifests.yaml: (object: application-service-system/application-service-controller-manager apps/v1, Kind=Deployment) container "manager" does not expose port 8081 for the HTTPGet (check: liveness-port, remediation: Check which ports you've exposed and ensure they match what you have specified in the liveness probe.)
/home/runner/work/application-service/application-service/.kube-linter/manifests.yaml: (object: application-service-system/application-service-controller-manager apps/v1, Kind=Deployment) container "manager" does not expose port 8081 for the HTTPGet (check: …
```
> Add container port to manager container (addresses kube-linter error)

- controllers/webhooks/component_webhook.go
This PR ensures that we retrieve the most recent version of the Component before updating its status.build-nudged-by field. The should prevent an issue where the nudging component isn't referenced in that field.
https://issues.redhat.com/projects/KFLUXBUGS/issues/KFLUXBUGS-1105
> [KFLUXBUGS-1105]: Retrieve Component before updating status for build-nudged-by

- docs/serviceability.md
Simply fixes a broken link to book of appstudio (currently gives 404) with a working one (https://redhat-appstudio.github.io/architecture/ref/index.html)
N/A - Part of devtools week
> [Devtools Week] Fix book of appstudio link

- Makefile
- cdq-analysis/pkg/util.go
- cdq-analysis/pkg/util_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
- controllers/component_controller_unit_test.go
- controllers/componentdetectionquery_controller.go
- controllers/componentdetectionquery_controller_test.go
The PR updates the `component_controller` to return a user error in case the `given` URL is not from a supported development platform (right now only github).
The necessary test cases have been added.
https://issues.redhat.com/browse/DEVHAS-628
> Return error for non supported development platform urls

- main.go
- pkg/availability/git.go
- pkg/availability/git_test.go
- pkg/github/github.go
- pkg/github/github_test.go
- pkg/github/mock.go
- pkg/metrics/git.go
- pkg/metrics/metrics.go
- Adds in the Availability metrics as per https://github.com/redhat-appstudio/o11y/tree/main/exporters/dsexporter 
- Inspired from https://github.com/konflux-ci/remote-secret/pull/338 
- Metric format specification at https://docs.google.com/document/d/193FO8DYP8zCzzued53DiIT84xmyTm51v_OqiWzQi8Bg/edit
- Makes a simple noop Git API call every 20 minutes (see screenshot below)
https://issues.redhat.com/browse/DEVHAS-597
The HAS pod will print the statements about availability:
> Add availability metrics

- gitops/generate_build.go
- gitops/generate_build_test.go
When onboarding self-hosted SCM PAC can't determine the the base url, so it should be provided explicitly.
Allow users to mention the provider (SCM) URL using an annotation on the component.
> RHTAPSRE-467: Support the configuration of provider URL

- controllers/component_controller.go
- controllers/component_controller_test.go
- pkg/metrics/component.go
This PR adds an extra condition upon component deletion. More detailed in https://github.com/redhat-appstudio/application-service/blob/main/controllers/component_controller.go#L191 we now check if the component's application has a deletion timestamp set. If yes we don't delete the component to avoid race conditions between the component & the application deletion.
https://issues.redhat.com/browse/DEVHAS-627
> Avoid race coditions from component deletion for applications already marked to be deleted

- controllers/webhooks/webhook_suite_test.go
- controllers/webhooks/webhooks.go
- go.mod
- go.sum
- main.go
This commit updates the `operator-toolkit` refrence
as a result of migration to `konflux-ci` from `redhat-appstudio`
More details parent EPIC:
https://issues.redhat.com/browse/RHTAPREL-800
https://issues.redhat.com/browse/RHTAPREL-806
> feat(RHTAPREL-806): update operator toolkit refrence

- controllers/component_controller.go
- controllers/component_controller_test.go
- pkg/util/util.go
- pkg/util/util_test.go
This PR tries to fix the metrics for component creation for cases of gitlab URLs by returning a user error on the `component_controller.go`
https://issues.redhat.com/browse/DEVHAS-628
> Fix metrics for component creation and gitlab url

- controllers/application_controller.go
- controllers/application_controller_test.go
- controllers/component_controller.go
- controllers/component_controller_test.go
Updates the Application and Component controllers to add back the finalizer removal code. Upon each reconcile of a resource, the controllers will check if the resource still has the finalizer present, and if so, removes it before completing reconciliation. This will also ensure that no resources have finalizers left when HAS is deprecated.
N/A, but relates to https://issues.redhat.com/browse/DEVHAS-648
> Handle finalizer removal

- .github/workflows/pr.yml
- Makefile
- config/webhook/manifests.yaml
- controllers/webhooks/component_webhook.go
- controllers/webhooks/component_webhook_unit_test.go
Updates the Component webhooks to add in logic to set the owner references. The defaulting webhook will check to see if the Component has the owner reference set every time the resource is created/updated, and if not set, it will update the resource to have it set.
https://issues.redhat.com/browse/KFLUXBUGS-1290
> [KFLUXBUGS-1290] Handle ownerrefs in webhook

- controllers/webhooks/component_webhook.go
- controllers/webhooks/component_webhook_unit_test.go
Updates the Component webhook to use the HAS kubeconfig and kube client to update the owner ref, rather than the one provided by the defaulting webhook, which averts the issue seen in https://issues.redhat.com/browse/KFLUXBUGS-1299
https://issues.redhat.com/browse/KFLUXBUGS-1299
> [KFLUXBUGS-1299] Use HAS kubeconfig to set ownerref

- .github/workflows/pr.yml
- .tekton/application-service-pull-request.yaml
- go.mod
- go.sum
- webhooks/webhook_suite_test.go
The component status CRD had a new field to it, but application-service would overwrite the field when anyone attempted to update it.  Updating application-service to the newest version of application-api fixes this issue
There isn't a story for this, but it unblocks an issue that will allow us to implement [STONEINTG-1008](https://issues.redhat.com/browse/STONEINTG-1008)
Deploy the change to a cluster.  Create a component on the cluster and patch it with `kubectl patch component --type json ${COMPONENT_NAME}  -p '{"status": {"lastPromotedImage": "quay.io/test/sample-image:latest"}}' --type merge --subresource status --dry-run=server -o yaml`.  Without this change the yaml output will not show `.status.lastPromotedImage`.  With this change it will.
> chore: update application-api version

- .tekton/application-service-pull-request.yaml
- .tekton/application-service-push.yaml
Need to fix these so that changes can be promoted in infra-deployments
> fix: update on-pull and on-push pipelines

- bundle/manifests/application-service.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
gcr.io is being decommissioned.
> chore: move to supported kube-rbac-proxy image

- bundle/manifests/application-service.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
* The etcd defragmentation is causing the leader election to fail frequently, crashing the service
Signed-off-by: dirgim <kpavic@redhat.com>
Disable leader election in controller manager
[KONFLUX-8822](https://issues.redhat.com//browse/KONFLUX-8822)
> fix(KONFLUX-8822): disable leader election
