samples/hasapplication/hasapp.yml
Add the missing sample referenced from docs/kcp.md
=> Add missing sample

.github/workflows/codecov.yml, .github/workflows/pr.yml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
=> DEVHAS-38 Add coverage upload to codecov.io

Dockerfile
Use registry.access.redhat.com/ubi8/ubi-minimal:8.4-210
=> Use the Red Hat UBI image from Red Hat registry

config/rbac/hasapplication_editor_role.yaml, config/rbac/hasapplication_viewer_role.yaml, config/rbac/hascomponent_editor_role.yaml, config/rbac/hascomponent_viewer_role.yaml, config/rbac/haspush_editor_role.yaml, config/rbac/haspush_viewer_role.yaml, config/rbac/hasservicedetectionquery_editor_role.yaml, config/rbac/hasservicedetectionquery_viewer_role.yaml, config/rbac/kustomization.yaml
Needed by https://github.com/redhat-appstudio/infra-deployments/pull/32
=> Add aggregation of roles

Dockerfile
=> WIP ensure container doesn't complain about root

controllers/build.go, controllers/build_test.go, controllers/component_controller_test.go
Use v0.1.4 and also pin it to the appropriate sha
=> use updated build bundle v0.1.4

samples/hasapplication/hascomp.yml
Add sample component for testing purposes.
=> Add component sample bound to application-sample

Makefile, config/crd/kustomization.yaml, config/crd/patches/cainjection_in_applications.yaml, config/crd/patches/cainjection_in_components.yaml, config/default/kustomization.yaml, config/default/webhookcainjection_patch.yaml, config/webhook/service.yaml
Based on what https://github.com/redhat-appstudio/service-provider-integration-operator does
=> Don't use cert-manager for webhooks

controllers/component_controller.go, controllers/component_controller_unit_test.go, gitops/generate.go, gitops/generate_build.go, gitops/generate_build_test.go, gitops/gitops_test.go
Reimplementation of https://github.com/redhat-appstudio/application-service/pull/42 using single commit
=> Add build gitops generation

.tekton/pull-request.yaml
To be used with https://github.com/redhat-appstudio/infra-deployments/pull/115
=> Setup CI using 'AppStudio Staging CI' based on Tekton

.tekton/pull-request.yaml
to avoid the error in https://github.com/redhat-appstudio/application-service/pull/58
=> Rename the pipelinerun yaml 

pkg/github/github.go
=> Make gitops repositories public by default

controllers/component_controller_test.go, gitops/generate_build.go, gitops/generate_build_test.go
part of https://github.com/redhat-appstudio/build-definitions/pull/33
=> resolve broken docker-build pipeline definition

.ci/README.md, .ci/oci-e2e-has.sh, .ci/openshift-ci/Dockerfile, .gitignore
The current PR create an mechanism to run the e2e framework in each PR.
[E2E framework documentation](https://github.com/redhat-appstudio/e2e-tests/tree/main/pkg/tests/has)
=> Run e2e appstudio tests in each PR

.tekton/push.yaml
Moving CI from infra-deployments to this repository.
=> Add push event for Pipeline as Code

gitops/generate.go, gitops/generate_test.go, gitops/resources/kustomization.go
Fixes https://issues.redhat.com/browse/DEVHAS-99
Updates the generated kustomization.yaml files to include the APIVersion and Kind fields
=> [DEVHAS-99] Add APIVersion and Kind to kustomize files

controllers/component_controller.go
This MR explicitly sets default component image in component spec if it was not set manually.
Such behavior:
- Makes it more clear for the user which image is used and how to change it.
- Analysis of the component (including gitops creation) is made from actual component configuration in the cluster, not a modified in-memory copy.
=> Update component spec with default image if the image is not set

config/rbac/role.yaml, controllers/component_controller.go, gitops/generate_build.go, gitops/generate_build_test.go, gitops/prepare/prepare.go, gitops/prepare/prepare_test.go
leverages infra @brunoapimentel established with https://github.com/redhat-appstudio/application-service/pull/106
=> PLNSRVCE-250: bypass mouting of appstudio pull secret as workspace secret volume if secret is not present

.ci/oci-e2e-has.sh
Create openshift user which are necessary for has tests
=> Add openshift ci custom user

gitops/generate_build.go, gitops/generate_build_test.go, main.go
@Michkov @sbose78 PTAL
my interpretation of @Michkov 's https://issues.redhat.com/browse/PLNSRVCE-251?focusedCommentId=20286643&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20286643
=> PLNSRVCE-251: protect against image pushes to quay.io/redhat-appstudio/user-workloads with mismatched user tags and namespaces

gitops/generate_build.go, gitops/generate_build_test.go
Default repostory should be protected against pushing from other
namespaces. The image tag name should start with namespace.
=> PLNSRVCE-251: fix matching of protected tags

gitops/prepare/prepare.go, gitops/prepare/prepare_test.go
The function can be used by other services to use the same build bundle.
=> Publish gitops.prepare.ResolveBuildBundle function

api/v1alpha1/componentdetectionquery_types.go, bundle/manifests/appstudio.redhat.com_componentdetectionqueries.yaml, config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml, controllers/componentdetectionquery_controller.go, controllers/componentdetectionquery_controller_test.go, controllers/constants.go, go.mod, go.sum, pkg/devfile/detect.go, pkg/devfile/detect_mock.go, pkg/devfile/devfile.go, pkg/devfile/devfile_test.go
This PR removes the `isMultiComponent` field from CDQ spec, and use the following strategy to detect multi component project:
1. scan root dir for devfile & dockerfile. If devfile/dockerfile exist, assume as it's single component. If no, proceed to step 2
2. run alizer at root dir, the following cases will be considered as multi component. and need to scan repo to proceed step3. 
- case 1: no components been detected by Alizer, might still has subfolders contains dockerfile(but no current supported devfile samples). Need to scan repo
- case 2: more than 1 components been detected by Alizer, is certain a multi-component project. Need to scan repo
- case 3: one or more than 1 compinents been detected by Alizer, and the first one in the list is under sub-folder. Need to scan repo.
3. search …
=> [DEVHAS-80] Multi component detection

.ci/oci-e2e-has.sh
Follow-up on https://github.com/redhat-appstudio/e2e-tests/pull/126/files
=> fix: openshift-ci script for running tests

config/kcp/apiexport_has.yaml, config/kcp/apiresourceschema_has.yaml
- Pulls in the isMultiComponent removal
=> Update KCP manifests

go.mod, go.sum
[Latest Alizer commit](https://github.com/redhat-developer/alizer/pull/100) fixed an important bug that affected component detection. This PR pulls in this change.
=> pull in latest alizer

.github/workflows/build.yml, Dockerfile
This PR will add multi-architecture support to the application-service operator image
=> Added ppc64le support

gitops/generate_build.go, gitops/generate_build_test.go, gitops/prepare/prepare.go, gitops/prepare/prepare_test.go
This PR adds ability to generate PaC repository object that uses webhook
=> Update generate Pipelies-as-Code repository gitops functions

gitops/generate_build.go, gitops/generate_build_test.go
=> Add gitlab url into PaC repository config

gitops/generate_build.go, gitops/generate_build_test.go, pkg/devfile/detect.go, pkg/devfile/detect_test.go
This change makes it easier to access other properties of an
ImageComponent.
=> Make SearchForDockerfile return DockerfileImage

.tekton/pull-request.yaml
=> Change max pipeline runs to 10

go.mod, go.sum
preserve patches order and pre-empt custom patches over newly generated ones
=> [DEVHAS-152] patches order in overlays kustomization file

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/CONTRIBUTING.md, docs/DCO
Adds in 
- Contributing.md
- DCO
- PR template
=> Add Contributing, DCO & PR Template

.github/workflows/build.yml, .github/workflows/codecov.yml, .github/workflows/pr.yml
There was inconsistent licensing in these files (EPL and Apache).  Since these files do not need licensing, we should remove them.
=> license removal from git workflows

gitops/generate_build.go
This is a further change for 1c1a0c0cbe7c4a7af6b4d81dd2d2352ee562b7e4 to make it reusable for the build-service.
- [n/a] Documentation 
- [n/a] Client Impact
=> Make a function to generate volumeClaimTemplate

controllers/component_controller.go
As discussed earlier, this code prevents HAS from retrieving the webhook route for Components when it's running on KCP. The Route API is not available on KCP, and since this is merely a cosmetic change to the Component status, it's best to remove it.
N/A
=> Don't get webhook route on KCP

controllers/component_controller.go
Updates the error message seen on https://issues.redhat.com/browse/DEVHAS-181 to be more user friendly
https://issues.redhat.com/browse/DEVHAS-181
N/A
=> [DEVHAS-181] Update Component Controller err msg

controllers/suite_test.go, go.mod, go.sum
This PR  update application-api version to pull in latest api change which adds additional columns in component, application and cdq printer.
https://issues.redhat.com/browse/DEVHAS-49
=> [DEVHAS-49]Add additional fields to CRDs get output

.github/workflows/pr.yml, Makefile, controllers/component_controller.go, pkg/github/mock.go, pkg/util/util.go
Enables gosec scans as part of our github actions workflow
https://issues.redhat.com/browse/DEVHAS-197
=> [DEVHAS-197] Enable Gosec and fix findings

controllers/application_controller.go, controllers/applicationsnapshotenvironmentbinding_controller.go, controllers/component_controller.go, controllers/componentdetectionquery_controller.go
Ensures log instances are not reused in order to avoid data being appended
https://issues.redhat.com/browse/DEVHAS-202
Tested manually on a local cluster and confirmed key/value pairs are not being appended
=> Avoid appending to audit logs

gitops/generate_build.go, gitops/generate_build_test.go
=> PLNSRVCE-693: set url without .git suffix in pac-repository.yaml

gitops/generate_build_test.go, gitops/prepare/prepare.go
Delete HACBS flag as AppStudio and HACBS are merged.
[PLNSRVCE-992](https://issues.redhat.com/browse/PLNSRVCE-992)
=> Delete isHACBS flag

config/monitoring/grafana-dashboards/has-gitops-repo-metrics.json, config/monitoring/kustomization.yaml
Add initial dashboard definition and configmap
https://issues.redhat.com/browse/DEVHAS-208
=> [DEVHAS-208] Add HAS grafana dashboard

.tekton/push.yaml, config/monitoring/grafana-dashboards/has-gitops-repo-metrics.json
- Updates sli dashboard to use template source
- Ensure hash is updated when there are changes to the dashboard files  
https://issues.redhat.com/browse/DEVHAS-208
=> [DEVHAS-208] Update sli dashboard

controllers/component_controller.go, go.mod, go.sum, pkg/devfile/devfile.go, pkg/devfile/devfile_test.go
overwrite the deployment/svc/route name and merge labels in base component
verified the base component generated with expected value: https://github.com/yangcao77/stephanie-app-yangcao-take-sit/blob/982e20242c695aefcb3f695a153ac0d694a4c8f8/components/devfile-sample-go-basic2/base/deployment.yaml#L6-L24
https://issues.redhat.com/browse/DEVHAS-247
=> [DEVHAS-247]overwrite the deployment/svc/route name and merge labels

go.mod, go.sum
Pulls in the latest Gitops Gen Library for the https://issues.redhat.com/browse/DEVHAS-218 fix
https://issues.redhat.com/browse/DEVHAS-218
All tests should pass
=> [DEVHAS-218] Pull in the latest gitops gen library

controllers/applicationsnapshotenvironmentbinding_controller.go, controllers/applicationsnapshotenvironmentbinding_controller_test.go
Don't overwrite the SEB labels
https://issues.redhat.com/browse/DEVHAS-250
- tests should pass
- create SEB with labels, confirm SEB controller should preserve them
=> Dont overwrite the SEB labels

controllers/application_controller.go, controllers/component_controller.go, gitops/generate.go, pkg/github/github.go, pkg/github/github_test.go, pkg/util/util.go
=> PLNSRVCE-773: avoid exposing username via built image tag

README.md
=> feat: Add doc link to help contribuitors to see how the e2e artifacts are in openshift CI

README.md, docs/gitops-generation.md
Add a link to the GitOps Gen Library in README
N/A
Adds a link to the GitOps Gen Repository
=> Add link to gitops gen module library in README

controllers/componentdetectionquery_controller.go, controllers/componentdetectionquery_controller_test.go
This issue remove the tailing  `/` from the `repoURL`. 
https://issues.redhat.com/browse/DEVHAS-277
=> [DEVHAS-277]fix tailing forward slash

Makefile, controllers/application_controller.go, controllers/application_controller_finalizer.go, controllers/applicationsnapshotenvironmentbinding_controller.go, controllers/component_controller.go, controllers/component_controller_unit_test.go, controllers/componentdetectionquery_controller.go, pkg/metrics/metrics.go
Adds prometheus metrics to count the various git operation calls
https://issues.redhat.com/browse/DEVHAS-272
=> Rate Limit metrics

pkg/devfile/devfile.go, pkg/devfile/devfile_test.go, pkg/spi/spi_mock.go
This PR updates the behavior when generating deployment-patch from devfile:
- If only one kubernetes component defined, directly use it. 
- if more than one kubernetes components defined, look for the one being referenced by default deploy command. 
https://issues.redhat.com/browse/DEVHAS-263
=> [DEVHAS-263] gitops generator check deploy cmd

controllers/componentdetectionquery_controller.go, controllers/componentdetectionquery_controller_test.go, controllers/update.go, controllers/update_test.go, pkg/devfile/detect.go, pkg/devfile/detect_mock.go
Updates the logic for CDQs to allow for ports to be detected in Dockerfile components. 
N/A
=> Port detection for Dockerfile components

controllers/component_controller.go, controllers/component_controller_conditions.go, controllers/suite_test.go, go.mod, go.sum
When a Custom Resource we're watching fails to update its status, we're only logging the error and not requeueing, which means it's possible (albeit very unlikely) for a given resource to get stuck. Generally this hasn't been an issue, and we haven't seen issues get stuck, but we've recently seen it happen more frequently for Component resources, as a result of changes involving the [image controller](https://github.com/redhat-appstudio/image-controller). 
To resolve this, I've updated the functions in `component_controller_conditions.go` to do two things:
1) If the status update fails, we get the latest version of the resource from the cached API server and re-attempt the status update
- This may not always be the most up to date version, so the following step is needed too
2) If the …
=> [DEVHAS-310] fix: Requeue if status update fails for Components

.tekton/push.yaml, config/monitoring/grafana-dashboards/has-rate-limiting-metrics.json, config/monitoring/kustomization.yaml
- Adds a new grafana dashboard for the rate limiting metrics which measures the  various git operation requests over a period of an hour using the [increase function](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase).  This does not include the primary and secondary rate metrics since those counters do not appear if they are not used and will be added later along with the additional token names we intend to provision
- Updates the tekton push.yaml file to update the stage and prod kustomization files
https://issues.redhat.com/browse/DEVHAS-272
=> [DEVHAS-272] add rate limiting dashboard

config/monitoring/grafana-dashboards/has-rate-limiting-metrics.json
Updates the dashboard to track additional metrics from the token pool.   
https://issues.redhat.com/browse/DEVHAS-351
=> update rate limiting dashboard - part 1

controllers/component_controller.go, controllers/component_controller_test.go, controllers/componentdetectionquery_controller.go, controllers/componentdetectionquery_controller_test.go, controllers/update.go, controllers/update_test.go, pkg/devfile/detect.go, pkg/devfile/detect_test.go, pkg/devfile/devfile.go, pkg/devfile/devfile_test.go, pkg/devfile/errors.go, pkg/devfile/errors_test.go, pkg/spi/spi_test.go
This PR utilized Dockerfile and Containerfile name to update all logging & error messages & comment to use the capitalized name, which is the file name we are looking for. 
https://issues.redhat.com/browse/DEVHAS-338
=> [DEVHAS-338] update Containerfile and Dockerfile name to be utilized

controllers/component_controller.go, controllers/component_controller_test.go
This PR updates the component controller and use revision set instead of hard-coded "main"
https://issues.redhat.com/browse/DEVHAS-320
=> [DEVHAS-320]remove hard coded main branch

config/monitoring/grafana-dashboards/has-rate-limiting-metrics.json
* update the charts in the rate limiting dashboard to include git operations that can be rate-limited and ones that aren't (for insights gathering)
* incorporated new metrics added for branch detection in the component controller by https://github.com/redhat-appstudio/application-service/pull/308
https://issues.redhat.com/browse/DEVHAS-356
=> [DEVHAS-356] update rate limiting dashboard

controllers/component_controller_test.go, controllers/suite_test.go, controllers/update.go, controllers/update_test.go, go.mod, go.sum, pkg/util/util.go, pkg/util/util_test.go
* picks up the new int pointer type from application-api
* updates logic in the component controller and test
https://issues.redhat.com/browse/RHTAPBUGS-12
=> [RHTAPBUGS-12] pick up latest changes from application-api and handle pointer values

pkg/github/token.go, pkg/github/token_mock.go, pkg/github/token_test.go, pkg/metrics/metrics.go
Adds additional metrics to detect what rate limit a given token has been subjected to and the remaining size of the token pool
https://issues.redhat.com/browse/DEVHAS-362
=> [DEVHAS-362] token pool metrics

pkg/github/token.go, pkg/github/token_mock.go, pkg/github/token_test.go, pkg/metrics/metrics.go
https://issues.redhat.com/browse/DEVHAS-362
What does this PR do?:
- Fixes failing metrics test case.  Previously, the mock token pool was increased to 2 to accommodate for conflicts but what wound up happening was, another test was passing in an empty token string which resulted in a random selection of the two tokens from the pool (which is why tests sometimes failed and sometimes passed).  The fix was to reduce the size of the pool down to 1 and increase the expected metrics count
- Also changed the counter vec to remove  "tokensRemaining" since we are counting the number of times a token has been primary/secondary rate limited,  we can determine the remaining tokens in a grafana query and use it in alerting eventually. 
Adds additional metrics to detect what rate limit a given token …
=> [DEVHAS-362] fix failing test

config/monitoring/grafana-dashboards/has-rate-limiting-metrics.json
Adds charts to capture newly added token pool metrics
https://issues.redhat.com/browse/DEVHAS-356
=> [DEVHAS-356] update dashboard with token pool metrics

go.mod, go.sum
This PR pulls in latest Alizer to fix the issue that alizer stucks at repo analysis
verified the cdq now complete within 95 secs:
```
Spec:
Git:
URL:  https://github.com/openshift/hive
Status:
Component Detected:
Hive - Usjv:
Component Stub:
Application:     insert-application-name
Component Name:  hive-usjv
Resources:
Source:
Git:
Context:         ./
Dockerfile URL:  Dockerfile
URL:             https://github.com/openshift/hive
Target Port:         8080
Language:              Dockerfile
Project Type:          Dockerfile
Conditions:
Last Transition Time:  2023-05-24T11:54:01Z
Message:               ComponentDetectionQuery is processing
Reason:                Success
Status:                True
Type:                  Processing
Last Transition Time:  2023-05-24T11:55:45Z
Message: …
```
=> [RHTAPBUGS-333] pull in latest alizer

OWNERS
Adds an OWNERS file so we can enable PaC runs
https://issues.redhat.com/browse/DEVHAS-386
=> [DEVHAS-386] add OWNERS file

.github/workflows/pact_postmerge.yml, controllers/application_pact_test.go
Add Pact tests running post-merge and publish their result.
https://issues.redhat.com/browse/HAC-2988
I don't know how to test post-merge GH action before merging here. I tested that in my own [fork](https://github.com/Katka92/application-service/actions/runs/5275847312).
=> Add Pact post-merge job

entrypoint.sh
https://issues.redhat.com/browse/RHTAPBUGS-435
=> [RHTAPBUGS-435] ensure args from pod get passed into entrypoint

controllers/applicationsnapshotenvironmentbinding_controller.go
To help with debugging why https://issues.redhat.com/browse/RHTAPBUGS-322 isn't fixed on prod.
=> Add log statements for SEB route name

controllers/componentdetectionquery_controller_test.go, controllers/update.go, controllers/update_test.go, go.mod, go.sum
Apply the changes that if `generateComponentName` has been set, do not check for component existence and directly generate component name with random chars appended. 
https://issues.redhat.com/browse/RHTAPBUGS-441
=> [RHTAPBUGS-441]make changes to random chars

controllers/applicationsnapshotenvironmentbinding_controller.go, controllers/applicationsnapshotenvironmentbinding_controller_test.go, controllers/mapper_test.go, go.mod, go.sum
This PR pulls in the latest application-api with the change that makes SEB replica an optional int pointer
https://issues.redhat.com/browse/RHTAPBUGS-173
=> [RHTAPBUGS-173] HAS change for making SEB replica an optional int pointer

go.mod, pkg/devfile/devfile.go, pkg/devfile/devfile_test.go
This PR updates the devfile validation function to filter out the warnings. 
Tested the reported issue has been fixed:
```
Status:
Component Detected:
cpx-components-2adv:
Component Stub:
Application:     insert-application-name
Component Name:  cpx-components-2adv
Resources:
Source:
Git:
Context:         ./
Dockerfile URL:  Containerfile
Revision:        main
URL:             https://github.com/chapeaux/cpx-components
Language:              Dockerfile
Project Type:          Dockerfile
```
https://issues.redhat.com/browse/RHTAPBUGS-466
=> [RHTAPBUGS-466]update the devfile validation

entrypoint.sh
Removes the feature flag to allow the fix to be deployed to prod
https://issues.redhat.com/browse/RHTAPBUGS-292
=> [RHTAPBUGS-292] Remove feature flag

Makefile, cdq-analysis/pkg/componentdetectionquery_test.go, cdq-analysis/pkg/detect.go, cdq-analysis/pkg/ioutils.go, cdq-analysis/pkg/ioutils_test.go, codecov.yml
This PR fix test bugs, and update the makefile to include cdq-analysis go module to the PR test. 
https://issues.redhat.com/browse/DEVHAS-425
=> [DEVHAS-425]fix test bug

.github/workflows/codecov.yml, .github/workflows/pact_postmerge.yml, .github/workflows/pr.yml, Dockerfile, cdq-analysis/go.mod, cdq-analysis/main.go, cdq-analysis/pkg/detect.go, cdq-analysis/pkg/detect_mock.go, cdq-analysis/pkg/devfile_test.go, cdq-analysis/pkg/util.go, go.mod, pkg/github/mock.go, pkg/util/ioutils/ioutils.go, pkg/util/util.go
this pr updates the go version to 1.19
https://issues.redhat.com/browse/DEVHAS-443
=> [DEVHAS-443]update to go 1.19

.github/workflows/pr.yml
=> DEVHAS-442: Add kube linter workflow

controllers/component_controller.go, controllers/component_controller_finalizer_test.go, pkg/metrics/metrics.go
Adds new component deletion metrics.  This is code change only, the remaining SLO documentation work, grafana dashboards, etc will be handled in a separate story.
https://issues.redhat.com/browse/DEVHAS-480
=> Component metrics

cdq-analysis/go.mod, cdq-analysis/go.sum, go.mod, go.sum
Pulls in latest Alizer from devfile org in order to fix [RHTAPBUGS-850](https://issues.redhat.com//browse/RHTAPBUGS-850)
https://issues.redhat.com/browse/RHTAPBUGS-850
=> [RHTAPBUGS-850] Update alizer version

controllers/application_controller.go, controllers/application_controller_test.go, controllers/update.go, controllers/update_test.go, pkg/metrics/metrics.go
This PR adds a new metric to HAS to track Application creation scenarios.
- `ApplicationCreationFailed` is incremented each time a system error occurs
- `ApplicationCreationSucceeded` is incremented each time Application creation succeeds *or* a user error occurred.
https://issues.redhat.com/browse/DEVHAS-481
N/A
N/A
=> [DEVHAS-481] Add Application Creation metrics

cdq-analysis/go.mod, cdq-analysis/go.sum, go.mod, go.sum
This PR updates library version to pull in the change from https://github.com/devfile/api/issues/1265
this supports to parse `devfile.yml`
https://issues.redhat.com/browse/DEVHAS-493
=> [DEVHAS-493]update library version

controllers/componentdetectionquery_controller.go
This PR adds another error when cdq configmap cannot be found or is nil.
be reported: https://redhat-internal.slack.com/archives/C02HZRGKDEY/p1698326309529429
=> Error when configmap cannot be found

.github/workflows/codecov.yml, controllers/start_test_env.go
Seeing if running `go mod download` beforehand fixes things
=> Try to fix code coverage reporting

pkg/devfile/devfile.go, pkg/devfile/devfile_test.go
reverts the [PR changes](https://github.com/redhat-appstudio/application-service/pull/423) to unblock promotion to prod
https://issues.redhat.com/browse/RHTAPBUGS-12
=> revert changes for RHTAPBUGS-12

controllers/applicationsnapshotenvironmentbinding_controller.go
Fix failing QE test reported in https://github.com/redhat-appstudio/infra-deployments/pull/2888
If replica is unset, it'll take the default gitops generator [replica](https://github.com/redhat-developer/gitops-generator/blob/c48f5bf6bf21b0785a255bcc5dd9b3d4fb516aed/api/v1alpha1/generator_options.go#L71) value which is 0 (default for int)
https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=13458&view=detail&selectedIssue=[RHTAPBUGS-12](https://issues.redhat.com//browse/RHTAPBUGS-12)
=> Replica fix for SEB

controllers/component_controller.go, controllers/component_controller_test.go, controllers/component_controller_unit_test.go, controllers/errors.go, controllers/update.go, pkg/devfile/devfile.go, pkg/devfile/errors.go, pkg/github/github.go, pkg/github/github_test.go, pkg/metrics/metrics.go
- Adds Prometheus metrics for Component creation
- Updates test to check for metrics 
https://issues.redhat.com/browse/DEVHAS-483
Tests should pass
=> Add Prometheus metrics for Component creation

Makefile, cdq-analysis/pkg/util.go, cdq-analysis/pkg/util_test.go, controllers/component_controller.go, controllers/component_controller_test.go, controllers/componentdetectionquery_controller.go, controllers/componentdetectionquery_controller_test.go
Reverts https://github.com/redhat-appstudio/application-service/pull/454
=> Revert "Return error for non supported development platform urls"

.tekton/application-service-pull-request.yaml, .tekton/application-service-push.yaml, Dockerfile
Required to merge https://github.com/redhat-appstudio/application-service/pull/465. Also updates labels on the Dockerfile to include new labels required by Enterprise Contract
=> Update params for image-check
